SELECT TABLE_CATALOG, TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,DATETIME_PRECISION
ORDINAL_POSITION,COLUMN_DEFAULT,IS_NULLABLE

FROM INFORMATION_SCHEMA.COLUMNS

SELECT TABLE_CATALOG,TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE

FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS


SELECT C.TABLE_CATALOG, C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE,TC.CONSTRAINT_NAME,TC.CONSTRAINT_TYPE,
C.NUMERIC_PRECISION,C.DATETIME_PRECISION,C.CHARACTER_MAXIMUM_LENGTH,C.ORDINAL_POSITION,C.COLUMN_DEFAULT,C.IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
ON C.TABLE_NAME = TC.TABLE_NAME AND C.TABLE_SCHEMA = TC.TABLE_SCHEMA
ORDER BY TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME

CREATE TABLE TempDBMetaData (
temp_TABLE_CATALOG VARCHAR(250),
temp_TABLE_SCHEMA VARCHAR(250),
temp_TABLE_NAME VARCHAR(250),
temp_COLUMN_NAME VARCHAR(250),
temp_DATA_TYPE VARCHAR(250),
temp_CONSTRATINT_NAME VARCHAR(250),
temp_CONSTARINT_TYPE VARCHAR(250),
temp_ORDINAL_POSITION INT
)
drop table TempDBMetaData

INSERT INTO TempDBMetaData (temp_TABLE_CATALOG,temp_TABLE_SCHEMA,temp_TABLE_NAME,temp_COLUMN_NAME,temp_DATA_TYPE,temp_CONSTRATINT_NAME,temp_CONSTARINT_TYPE,temp_ORDINAL_POSITION)
SELECT C.TABLE_CATALOG, C.TABLE_SCHEMA,C.TABLE_NAME,C.COLUMN_NAME,C.DATA_TYPE,TC.CONSTRAINT_NAME,TC.CONSTRAINT_TYPE,
C.ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
ON C.TABLE_NAME = TC.TABLE_NAME AND C.TABLE_SCHEMA = TC.TABLE_SCHEMA
ORDER BY TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME

SELECT * From TempDBMetaData



tem